version: '3.8'

services:
  web:
    build: ./app
    command: gunicorn deals.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env
  web-static:
    build: ./app
    volumes:
      - static_volume:/home/app/web/staticfiles
    env_file: .env
    command: python manage.py collectstatic
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    volumes_from:
      - web
      - web-static
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  static_volume: